import "bootstrap/dist/css/bootstrap.min.css";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import LayoutClientWrapper from "@/components/LayoutClientWrapper";
import { ThemeProvider } from "@/context/ThemeContext";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"
        />
      </head>
      <body className={montserrat.variable}>
        <ThemeProvider>
          <Navbar />
          <LayoutClientWrapper>
            {children}
          </LayoutClientWrapper>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}